version: '2.1'
services:
  nginx:
    image: armdocker.seli.gic.ericsson.se/proj_openstack_tooling/dit_reverse_proxy:${UPGRADE_VERSION}
    restart: always
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      nodejs:
        condition: service_healthy
      nodejs2:
        condition: service_healthy
      swagger:
        condition: service_healthy
      helpdocs:
        condition: service_healthy
    volumes:
      - ./config/sslcerts:/etc/nginx/certs
    healthcheck:
      test: [ "CMD-SHELL","whoami || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 5
  nodejs:
    image: armdocker.seli.gic.ericsson.se/proj_openstack_tooling/deployment_inventory_tool:${UPGRADE_VERSION}
    restart: always
    environment:
     - DB_1_PORT_27017_TCP_ADDR=mongodb
     - LDAP_URL=${LDAP_URL}
     - SEARCH_FILTER=${SEARCH_FILTER}
     - BASE_DN_LIST=${BASE_DN_LIST}
     - PARAMETER_DEFAULTS_APPLICATION=${PARAMETER_DEFAULTS_APPLICATION}
     - JIRA_HOST=${JIRA_HOST}
     - JIRA_USERNAME=${JIRA_USERNAME}
     - JIRA_PASSWORD=${JIRA_PASSWORD}
     - UPGRADE_TOOL_URL=${UPGRADE_TOOL_URL}
     - DIT_EMAIL_ADDRESS=${DIT_EMAIL_ADDRESS}
     - DTT_EMAIL_ADDRESS=${DTT_EMAIL_ADDRESS}
     - DTT_EMAIL_PASSWORD=${DTT_EMAIL_PASSWORD}
     - TEAM_EMAIL=${TEAM_EMAIL}
     - IPV4REGEX=${IPV4REGEX}
     - IPV6REGEX=${IPV6REGEX}
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL","whoami || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 5
  nodejs2:
    image: armdocker.seli.gic.ericsson.se/proj_openstack_tooling/deployment_inventory_tool:${UPGRADE_VERSION}
    restart: always
    environment:
     - DB_1_PORT_27017_TCP_ADDR=mongodb
     - LDAP_URL=${LDAP_URL}
     - SEARCH_FILTER=${SEARCH_FILTER}
     - BASE_DN_LIST=${BASE_DN_LIST}
     - PARAMETER_DEFAULTS_APPLICATION=${PARAMETER_DEFAULTS_APPLICATION}
     - JIRA_HOST=${JIRA_HOST}
     - JIRA_USERNAME=${JIRA_USERNAME}
     - JIRA_PASSWORD=${JIRA_PASSWORD}
     - UPGRADE_TOOL_URL=${UPGRADE_TOOL_URL}
     - DIT_EMAIL_ADDRESS=${DIT_EMAIL_ADDRESS}
     - DTT_EMAIL_ADDRESS=${DTT_EMAIL_ADDRESS}
     - DTT_EMAIL_PASSWORD=${DTT_EMAIL_PASSWORD}
     - TEAM_EMAIL=${TEAM_EMAIL}
     - IPV4REGEX=${IPV4REGEX}
     - IPV6REGEX=${IPV6REGEX}
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL","whoami || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 5
  mongodb:
    image: armdocker.seli.gic.ericsson.se/dockerhub-ericsson-remote/mongo:4.0.14
    restart: always
    volumes:
     - mongodb_data:/data/db
     - mongodb_logs:/var/log/mongodb
    healthcheck:
      test: [ "CMD-SHELL","whoami || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 5
  swagger:
    image: armdocker.seli.gic.ericsson.se/proj_openstack_tooling/dit_api_docs:${UPGRADE_VERSION}
    restart: always
    environment:
     - API_URL=/apidocs/swagger.json
    healthcheck:
      test: [ "CMD-SHELL","whoami || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 5
  helpdocs:
    image: armdocker.seli.gic.ericsson.se/proj_openstack_tooling/dit_help_docs:${UPGRADE_VERSION}
    restart: always
    healthcheck:
      test: [ "CMD-SHELL","whoami || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 5

volumes:
  mongodb_data:
  mongodb_logs:
