apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - image: armdocker.seli.gic.ericsson.se/proj_openstack_tooling/deployment_inventory_tool
        name: web
        ports:
        - name: http-server
          containerPort: 80
        env:
        - name: MONGODB_URI
          value: "mongodb://mongo-0.mongo,mongo-1.mongo,mongo-2.mongo?replicaSet=rs0"
